# Use the official Node.js LTS image as the base image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the dependencies
RUN npm install --production

# Copy the rest of the application files to the container
COPY . .

# Build the NestJS application (this assumes you have already built your application)
RUN npm run build

# Expose the port on which your NestJS application is running
EXPOSE 3000

# Start the NestJS application in production mode
CMD ["npm", "run", "start:prod"]
