FROM node:16-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install -g @nestjs/cli
# RUN npm install bcrypt

RUN npm install --omit=dev

COPY . .

ENV DATABASE_URL=file:./dev.db
ENV JWT_SECRET_KEY=2#8k%xo=9hae8yv&88sci6bwr0*+6dp%*xig2&_bwdc623HJ%^889T

RUN npx prisma generate
RUN npx prisma migrate dev

RUN npm run build


CMD ["npm", "run", "start:prod"]
