version: "3.8"
services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nestjs-app
    container_name: nestjs-app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL="file:./dev.db"
      - JWT_SECRET_KEY="2#8k%xo=9hae8yv&88sci6bwr0*+6dp%*xig2&_bwdc623HJ%^889T"

